// Package parity implements the parity harness that compares legacy
// GoraphDB output against new SQLite output after a projection that
// strips Rung-0-introduced fields.
//
// At Rung 0, the harness runs against both tiers:
//   - testdata/parity/synthetic/ — hand-crafted, fast
//   - testdata/parity/real/ — real-world, realistic
//
// The harness is invoked as standard Go tests (go test ./internal/parity).
// It does NOT import the legacy GoraphDB path — it compares *query output*
// that was generated by each path and serialized to JSON.
package parity

import "encoding/json"

// StripProjection removes fields that are new in Rung 0 from a JSON
// blob so that legacy and new outputs can be compared byte-exactly.
//
// Strip list: id, environment, identity_source, pipeline_references,
// recent_traces, contract_history, upstream_storage,
// downstream_storage, boundaries, boundary_signal
var stripKeys = map[string]bool{
	"id":                  true,
	"environment":         true,
	"identity_source":     true,
	"pipeline_references": true,
	"recent_traces":       true,
	"contract_history":    true,
	"upstream_storage":    true,
	"downstream_storage":  true,
	"boundaries":          true,
	"boundary_signal":     true,
}

// StripFields removes the Rung-0-introduced keys from a JSON map
// recursively. Mutates in place.
func StripFields(v interface{}) interface{} {
	switch val := v.(type) {
	case map[string]interface{}:
		for k := range val {
			if stripKeys[k] {
				delete(val, k)
			} else {
				val[k] = StripFields(val[k])
			}
		}
		return val
	case []interface{}:
		for i := range val {
			val[i] = StripFields(val[i])
		}
		return val
	}
	return v
}

// ProjectAndMarshal parses JSON, strips Rung-0 fields, and re-marshals
// for comparison.
func ProjectAndMarshal(data []byte) ([]byte, error) {
	var raw interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	raw = StripFields(raw)
	return json.Marshal(raw)
}

// Divergence describes an intentional bug fix that the parity harness
// must accept rather than treat as a failure. Stored in
// testdata/parity/parity_divergences.json.
type Divergence struct {
	Query         string `json:"query"`
	Fixture       string `json:"fixture"`
	Justification string `json:"justification"`
}
