package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/pressly/goose/v3"
	_ "modernc.org/sqlite"

	"github.com/codevalent/cvalent/internal/model"
	"github.com/codevalent/cvalent/internal/store/migrations"
)

// Epoch is the valid_from value used for every Rung 0 row. Rung 2
// introduces real timestamps; until then every row is "valid since the
// beginning of time."
const Epoch = "1970-01-01T00:00:00Z"

// Store is the cvalent storage layer wrapping a single *sql.DB.
//
// At Rung 0 the only backend is SQLite via modernc.org/sqlite. The
// queries are intentionally hand-written here rather than generated by
// sqlc — they share the same SQL files (internal/store/queries/*) and
// are designed so that swapping in a generated Querier later is a
// drop-in replacement.
//
// Every read goes through the `valid_until IS NULL` filter (the
// "current state" view). Every insert stamps `valid_from = epoch,
// valid_until = NULL`. Bitemporal write semantics arrive in Rung 2.
type Store struct {
	db *sql.DB
}

// Open opens the SQLite store at `path` (use ":memory:" for an
// ephemeral store) and runs goose.Up against the embedded migrations.
// The returned Store is ready to use.
func Open(ctx context.Context, path string) (*Store, error) {
	dsn := path
	if path != ":memory:" {
		dsn = path + "?_pragma=foreign_keys(1)&_pragma=journal_mode(WAL)"
	}
	db, err := sql.Open("sqlite", dsn)
	if err != nil {
		return nil, fmt.Errorf("store: open: %w", err)
	}
	if err := db.PingContext(ctx); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("store: ping: %w", err)
	}

	goose.SetBaseFS(migrations.SQLite())
	if err := goose.SetDialect("sqlite3"); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("store: set dialect: %w", err)
	}
	goose.SetLogger(goose.NopLogger())
	if err := goose.UpContext(ctx, db, "sqlite"); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("store: migrate: %w", err)
	}

	return &Store{db: db}, nil
}

// Close closes the underlying database connection.
func (s *Store) Close() error {
	if s == nil || s.db == nil {
		return nil
	}
	return s.db.Close()
}

// DB returns the underlying *sql.DB. Used by the migrator and tests
// that need transactional control.
func (s *Store) DB() *sql.DB { return s.db }

// ErrNotFound is returned by Get* methods when no current row matches.
var ErrNotFound = errors.New("store: not found")

// UpsertNode inserts or updates a Node + FunctionMeta pair.
//
// At Rung 0 this is a simple INSERT OR REPLACE on (id, valid_from)
// because every row uses Epoch as valid_from. Rung 2 will replace this
// with an SCD2-style "close current row, insert new" pattern.
func (s *Store) UpsertNode(ctx context.Context, fn model.FunctionNode) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if err := upsertNodeTx(ctx, tx, fn); err != nil {
		return err
	}
	return tx.Commit()
}

func upsertNodeTx(ctx context.Context, tx *sql.Tx, fn model.FunctionNode) error {
	if fn.ID == uuid.Nil {
		return errors.New("store: UpsertNode: nil UUID")
	}
	idBytes, _ := fn.ID.MarshalBinary()

	if _, err := tx.ExecContext(ctx, `
		INSERT OR REPLACE INTO nodes
			(id, valid_from, valid_until, environment, kind, qualified_name,
			 name, distribution, module_path, language, file, identity_source, source)
		VALUES (?, ?, NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'parsed')`,
		idBytes, Epoch,
		string(fn.Environment), string(fn.Kind), fn.QualifiedName,
		fn.Name, fn.Distribution, fn.ModulePath, fn.Language, fn.File,
		string(fn.IdentitySource),
	); err != nil {
		return fmt.Errorf("store: insert node: %w", err)
	}

	paramsJSON, _ := json.Marshal(fn.Params)
	returnsJSON, _ := json.Marshal(fn.Returns)
	if _, err := tx.ExecContext(ctx, `
		INSERT OR REPLACE INTO node_function_meta
			(node_id, valid_from, valid_until, start_line, end_line,
			 exported, tag, receiver, pointer_receiver,
			 params, returns, contract_completeness)
		VALUES (?, ?, NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		idBytes, Epoch,
		fn.StartLine, fn.EndLine,
		boolInt(fn.Exported), fn.Tag, fn.Receiver, boolInt(fn.PointerReceiver),
		string(paramsJSON), string(returnsJSON), fn.ContractCompleteness,
	); err != nil {
		return fmt.Errorf("store: insert function meta: %w", err)
	}
	return nil
}

// UpsertNodeTx is the same as UpsertNode but runs inside an
// externally-managed *sql.Tx. The migrator uses this to land an entire
// migration in a single transaction so that partial failure rolls back
// cleanly.
func (s *Store) UpsertNodeTx(ctx context.Context, tx *sql.Tx, fn model.FunctionNode) error {
	return upsertNodeTx(ctx, tx, fn)
}

// UpsertNodes is a batched UpsertNode wrapped in a single transaction.
func (s *Store) UpsertNodes(ctx context.Context, fns []model.FunctionNode) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	for _, fn := range fns {
		if err := upsertNodeTx(ctx, tx, fn); err != nil {
			return err
		}
	}
	return tx.Commit()
}

// GetNode returns the current Node + FunctionMeta for the given UUID.
// Returns ErrNotFound if no current row exists.
func (s *Store) GetNode(ctx context.Context, id uuid.UUID) (model.FunctionNode, error) {
	idBytes, _ := id.MarshalBinary()
	row := s.db.QueryRowContext(ctx, `
		SELECT n.id, n.environment, n.kind, n.qualified_name, n.name,
		       n.distribution, n.module_path, n.language, n.file, n.identity_source,
		       m.start_line, m.end_line, m.exported, m.tag, m.receiver, m.pointer_receiver,
		       m.params, m.returns, m.contract_completeness
		FROM nodes n
		LEFT JOIN node_function_meta m
		  ON m.node_id = n.id AND m.valid_until IS NULL
		WHERE n.id = ? AND n.valid_until IS NULL`, idBytes)
	return scanFunctionNode(row)
}

// ListNodesByKind returns every current node of the given Kind.
func (s *Store) ListNodesByKind(ctx context.Context, kind model.Kind) ([]model.FunctionNode, error) {
	rows, err := s.db.QueryContext(ctx, `
		SELECT n.id, n.environment, n.kind, n.qualified_name, n.name,
		       n.distribution, n.module_path, n.language, n.file, n.identity_source,
		       m.start_line, m.end_line, m.exported, m.tag, m.receiver, m.pointer_receiver,
		       m.params, m.returns, m.contract_completeness
		FROM nodes n
		LEFT JOIN node_function_meta m
		  ON m.node_id = n.id AND m.valid_until IS NULL
		WHERE n.kind = ? AND n.valid_until IS NULL
		ORDER BY n.qualified_name`, string(kind))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []model.FunctionNode
	for rows.Next() {
		fn, err := scanFunctionNode(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, fn)
	}
	return out, rows.Err()
}

// scanner abstracts *sql.Row and *sql.Rows for scanFunctionNode.
type scanner interface {
	Scan(dest ...any) error
}

func scanFunctionNode(s scanner) (model.FunctionNode, error) {
	var (
		fn        model.FunctionNode
		idBytes   []byte
		paramsRaw sql.NullString
		retsRaw   sql.NullString
		envStr    string
		kindStr   string
		idSrcStr  string
		recv      sql.NullString
		ptrRecv   sql.NullInt64
		startLine sql.NullInt64
		endLine   sql.NullInt64
		exported  sql.NullInt64
		tag       sql.NullString
		complete  sql.NullString
	)
	if err := s.Scan(
		&idBytes, &envStr, &kindStr, &fn.QualifiedName, &fn.Name,
		&fn.Distribution, &fn.ModulePath, &fn.Language, &fn.File, &idSrcStr,
		&startLine, &endLine, &exported, &tag, &recv, &ptrRecv,
		&paramsRaw, &retsRaw, &complete,
	); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return fn, ErrNotFound
		}
		return fn, err
	}
	id, err := uuid.FromBytes(idBytes)
	if err != nil {
		return fn, fmt.Errorf("store: bad uuid bytes: %w", err)
	}
	fn.ID = id
	fn.Environment = model.Environment(envStr)
	fn.Kind = model.Kind(kindStr)
	fn.IdentitySource = model.IdentitySource(idSrcStr)
	fn.StartLine = int(startLine.Int64)
	fn.EndLine = int(endLine.Int64)
	fn.Exported = exported.Int64 != 0
	fn.Tag = tag.String
	fn.Receiver = recv.String
	fn.PointerReceiver = ptrRecv.Int64 != 0
	fn.ContractCompleteness = complete.String
	if paramsRaw.Valid && paramsRaw.String != "" {
		_ = json.Unmarshal([]byte(paramsRaw.String), &fn.Params)
	}
	if retsRaw.Valid && retsRaw.String != "" {
		_ = json.Unmarshal([]byte(retsRaw.String), &fn.Returns)
	}
	return fn, nil
}

// Edge represents an edge row for upsert / read.
type Edge struct {
	ID     uuid.UUID
	From   uuid.UUID
	To     uuid.UUID
	Kind   string
	Source string
	Meta   map[string]any
}

// UpsertEdge inserts or replaces an edge row.
func (s *Store) UpsertEdge(ctx context.Context, e Edge) error {
	if e.ID == uuid.Nil {
		return errors.New("store: UpsertEdge: nil UUID")
	}
	idBytes, _ := e.ID.MarshalBinary()
	from, _ := e.From.MarshalBinary()
	to, _ := e.To.MarshalBinary()
	src := e.Source
	if src == "" {
		src = "parsed"
	}
	metaJSON, _ := json.Marshal(orEmptyMap(e.Meta))
	_, err := s.db.ExecContext(ctx, `
		INSERT OR REPLACE INTO edges
			(id, valid_from, valid_until, from_node, to_node, kind, source, meta)
		VALUES (?, ?, NULL, ?, ?, ?, ?, ?)`,
		idBytes, Epoch, from, to, e.Kind, src, string(metaJSON))
	return err
}

// ListEdgesByKind returns every current edge of the given kind.
func (s *Store) ListEdgesByKind(ctx context.Context, kind string) ([]Edge, error) {
	rows, err := s.db.QueryContext(ctx, `
		SELECT id, from_node, to_node, kind, source, meta
		FROM edges
		WHERE kind = ? AND valid_until IS NULL`, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Edge
	for rows.Next() {
		var (
			idB, fromB, toB []byte
			e               Edge
			metaRaw         string
		)
		if err := rows.Scan(&idB, &fromB, &toB, &e.Kind, &e.Source, &metaRaw); err != nil {
			return nil, err
		}
		e.ID, _ = uuid.FromBytes(idB)
		e.From, _ = uuid.FromBytes(fromB)
		e.To, _ = uuid.FromBytes(toB)
		_ = json.Unmarshal([]byte(metaRaw), &e.Meta)
		out = append(out, e)
	}
	return out, rows.Err()
}

func boolInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

func orEmptyMap(m map[string]any) map[string]any {
	if m == nil {
		return map[string]any{}
	}
	return m
}
